<a href="https://colab.research.google.com/github/EricVPereira/Inteligencia-Artificial-Trabalho/blob/main/Entrega_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Entrega I

In [ ]:
import pandas as pd #Importa a biblioteca Pandas

In [ ]:
!wget 'https://www.kaggle.com/code/thiagobg/procon-dataset-overview/data?select=reclamacoes-fundamentadas-sindec-2012.csv' #Importa os arquivos utilizados
!wget 'https://www.kaggle.com/code/thiagobg/procon-dataset-overview/data?select=reclamacoes-fundamentadas-sindec-2013.csv'
!wget 'https://www.kaggle.com/code/thiagobg/procon-dataset-overview/data?select=reclamacoes-fundamentadas-sindec-2014.csv'
!wget 'https://www.kaggle.com/code/thiagobg/procon-dataset-overview/data?select=reclamacoes-fundamentadas-sindec-2015.csv'
!wget 'https://www.kaggle.com/code/thiagobg/procon-dataset-overview/data?select=reclamacoes-fundamentadas-sindec-2016.csv'

--2022-08-28 23:06:11--  https://www.kaggle.com/code/thiagobg/procon-dataset-overview/data?select=reclamacoes-fundamentadas-sindec-2012.csv
Resolving www.kaggle.com (www.kaggle.com)... 35.244.233.98
Connecting to www.kaggle.com (www.kaggle.com)|35.244.233.98|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘data?select=reclamacoes-fundamentadas-sindec-2012.csv’

data?select=reclama     [ <=>                ]  19.60K   102KB/s    in 0.2s

2022-08-28 23:06:12 (102 KB/s) - ‘data?select=reclamacoes-fundamentadas-sindec-2012.csv’ saved [20069]

--2022-08-28 23:06:12--  https://www.kaggle.com/code/thiagobg/procon-dataset-overview/data?select=reclamacoes-fundamentadas-sindec-2013.csv
Resolving www.kaggle.com (www.kaggle.com)... 35.244.233.98
Connecting to www.kaggle.com (www.kaggle.com)|35.244.233.98|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘data?select=reclamacoes-fundamentadas-sindec-2013.csv’

data?select=reclama     [ <=>                ]  19.60K   101KB/s    in 0.2s

2022-08-28 23:06:12 (101 KB/s) - ‘data?select=reclamacoes-fundamentadas-sindec-2013.csv’ saved [20069]

--2022-08-28 23:06:13--  https://www.kaggle.com/code/thiagobg/procon-dataset-overview/data?select=reclamacoes-fundamentadas-sindec-2014.csv
Resolving www.kaggle.com (www.kaggle.com)... 35.244.233.98
Connecting to www.kaggle.com (www.kaggle.com)|35.244.233.98|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘data?select=reclamacoes-fundamentadas-sindec-2014.csv’

data?select=reclama     [ <=>                ]  19.66K   101KB/s    in 0.2s

2022-08-28 23:06:13 (101 KB/s) - ‘data?select=reclamacoes-fundamentadas-sindec-2014.csv’ saved [20129]

--2022-08-28 23:06:13--  https://www.kaggle.com/code/thiagobg/procon-dataset-overview/data?select=reclamacoes-fundamentadas-sindec-2015.csv
Resolving www.kaggle.com (www.kaggle.com)... 35.244.233.98
Connecting to www.kaggle.com (www.kaggle.com)|35.244.233.98|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘data?select=reclamacoes-fundamentadas-sindec-2015.csv’

data?select=reclama     [ <=>                ]  19.60K   105KB/s    in 0.2s

2022-08-28 23:06:14 (105 KB/s) - ‘data?select=reclamacoes-fundamentadas-sindec-2015.csv’ saved [20069]

--2022-08-28 23:06:14--  https://www.kaggle.com/code/thiagobg/procon-dataset-overview/data?select=reclamacoes-fundamentadas-sindec-2016.csv
Resolving www.kaggle.com (www.kaggle.com)... 35.244.233.98
Connecting to www.kaggle.com (www.kaggle.com)|35.244.233.98|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘data?select=reclamacoes-fundamentadas-sindec-2016.csv’

data?select=reclama     [ <=>                ]  19.60K   109KB/s    in 0.2s

2022-08-28 23:06:15 (109 KB/s) - ‘data?select=reclamacoes-fundamentadas-sindec-2016.csv’ saved [20069]

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/Datasets/reclamacoes-fundamentadas-sindec-2012.csv', nrows=1000) #Le o arquivo reclamacoes-fundamentadas-sindec-2012.csv
df2 = pd.read_csv('/content/drive/MyDrive/Datasets/reclamacoes-fundamentadas-sindec-2013.csv', nrows=3000) #Le o arquivo reclamacoes-fundamentadas-sindec-2013.csv
df3 = pd.read_csv('/content/drive/MyDrive/Datasets/reclamacoes-fundamentadas-sindec-2014.csv', nrows=3000) #Le o arquivo reclamacoes-fundamentadas-sindec-2014.csv
df4 = pd.read_csv('/content/drive/MyDrive/Datasets/reclamacoes-fundamentadas-sindec-2015.csv', nrows=3000) #Le o arquivo reclamacoes-fundamentadas-sindec-2015.csv
df5 = pd.read_csv('/content/drive/MyDrive/Datasets/reclamacoes-fundamentadas-sindec-2016.csv', nrows=3000) #Le o arquivo reclamacoes-fundamentadas-sindec-2016.csv

In [ ]:
df1.shape, df2.shape, df3.shape, df4.shape, df5.shape #Mostra quantidade de colunas e registros

((1000, 23), (3000, 23), (3000, 23), (3000, 23), (3000, 23))

In [ ]:
df1.sample(2) #Pega dois elementos do primeiro dataset

,AnoCalendario,DataArquivamento,DataAbertura,CodigoRegiao,Regiao,UF,strRazaoSocial,strNomeFantasia,Tipo,NumeroCNPJ,...,CNAEPrincipal,DescCNAEPrincipal,Atendida,CodigoAssunto,DescricaoAssunto,CodigoProblema,DescricaoProblema,SexoConsumidor,FaixaEtariaConsumidor,CEPConsumidor
84,2012,2012-01-05 12:34:28.000,2010-06-17 09:38:57.000,1,Norte,AP,P. L. CAMPOS,TOQUE DE CARINHO/TOQUE INTELIGENTE,1,7.967054e+12,...,4789002.0,COMÉRCIO VAREJISTA DE PLANTAS E FLORES NATURAIS,N,73,Estabelecimento / Loja - Compra a Prazo,28,Cobrança indevida.,M,entre 61 a 70 anos,68902892
472,2012,2012-02-13 16:35:38.000,2011-04-26 10:10:13.000,3,Sudeste,MG,VIA VAREJO,PONTO FRIO,1,3.304126e+13,...,4713001.0,LOJAS DE DEPARTAMENTOS OU MAGAZINES,N,122,Móveis Para Quarto,120,Cobrança de valor quando o produto e devolvido...,F,entre 41 a 50 anos,35701347

In [ ]:
df2.sample(2) #Pega dois elementos do segundo dataset

,AnoCalendario,DataArquivamento,DataAbertura,CodigoRegiao,Regiao,UF,strRazaoSocial,strNomeFantasia,Tipo,NumeroCNPJ,...,CNAEPrincipal,DescCNAEPrincipal,Atendida,CodigoAssunto,DescricaoAssunto,CodigoProblema,DescricaoProblema,SexoConsumidor,FaixaEtariaConsumidor,CEPConsumidor
25,2013,2013-04-01 12:38:02.000,2012-12-13 10:01:08.000,2,Nordeste,RN,ALEX RODAS,ALEX RODAS,1,NaN,...,NaN,NaN,S,89,"Acessório Para Veículo ( Alarme, Amortecedor, ...",102,"Garantia (Abrangência, cobertura, etc.)",M,entre 41 a 50 anos,59000000.0
495,2013,2013-09-27 16:37:25.000,2013-01-30 12:49:09.000,2,Nordeste,BA,HIPERCARD BANCO MULTIPLO S.A.,HIPERCARD BANCO MULTIPLO,1,3.012230e+12,...,6422100.0,"BANCOS MÚLTIPLOS, COM CARTEIRA COMERCIAL",S,54,Cartão de Crédito,28,Cobrança indevida.,F,entre 51 a 60 anos,40235430.0

In [ ]:
df3.sample(2) #Pega dois elementos do terceiro dataset

,AnoCalendario,DataArquivamento,DataAbertura,CodigoRegiao,Regiao,UF,strRazaoSocial,strNomeFantasia,Tipo,NumeroCNPJ,...,CNAEPrincipal,DescCNAEPrincipal,Atendida,CodigoAssunto,DescricaoAssunto,CodigoProblema,DescricaoProblema,SexoConsumidor,FaixaEtariaConsumidor,CEPConsumidor
2615,2014,2014-01-03 17:20:41.000,2013-05-02 11:14:56.000,2,Nordeste,BA,TELEMAR NORTE LESTE S/A,TELEMAR - OI,1,3.300012e+13,...,6110801.0,SERVIÇOS DE TELEFONIA FIXA COMUTADA - STFC,N,279,Informática (Ex.:Provedor de Acesso a Internet),194,Cobrança indevida/abusiva,M,entre 51 a 60 anos,41213770.0
263,2014,2014-02-26 12:08:11.000,2013-02-18 12:57:53.000,1,Norte,AC,LOSANGO PROMOCOES DE VENDAS LTDA,LOSANGO,1,5.281313e+12,...,7490104.0,ATIVIDADES DE INTERMEDIAÇÃO E AGENCIAMENTO DE ...,N,63,Financeira,32,Calculo de prestação em atraso,F,entre 31 a 40 anos,NaN

In [ ]:
df4.sample(2) #Pega dois elementos do quarto dataset

,AnoCalendario,DataArquivamento,DataAbertura,CodigoRegiao,Regiao,UF,strRazaoSocial,strNomeFantasia,Tipo,NumeroCNPJ,...,CNAEPrincipal,DescCNAEPrincipal,Atendida,CodigoAssunto,DescricaoAssunto,CodigoProblema,DescricaoProblema,SexoConsumidor,FaixaEtariaConsumidor,CEPConsumidor
660,2015,2015-12-14 09:54:10.000,2015-10-30 11:38:12.000,3,Sudeste,SP,MAGAZINE LUIZA S.A.,MAGAZINE LUIZA - SAC/PROCON,1,4.796095e+13,...,4713001.0,LOJAS DE DEPARTAMENTOS OU MAGAZINES,N,134,"Produto de Uso Pessoal ( Barbeador, Depilador,...",109,Publicidade enganosa,F,entre 31 a 40 anos,14407346.0
1193,2015,2015-01-30 15:00:52.000,2014-10-02 10:43:22.000,3,Sudeste,ES,ROYAL E SUNALLIANCE SEGUROS S/A,ROYAL SEGUROS,1,3.306570e+13,...,6512000.0,SEGUROS NÃO-VIDA,S,282,Seguro,202,Roubo/furto,M,entre 21 a 30 anos,29140000.0

In [ ]:
df5.sample(2) #Pega dois elementos do quinto dataset

,AnoCalendario,DataArquivamento,DataAbertura,CodigoRegiao,Regiao,UF,strRazaoSocial,strNomeFantasia,Tipo,NumeroCNPJ,...,CNAEPrincipal,DescCNAEPrincipal,Atendida,CodigoAssunto,DescricaoAssunto,CodigoProblema,DescricaoProblema,SexoConsumidor,FaixaEtariaConsumidor,CEPConsumidor
2704,2016,2016-01-11 16:21:45.000,2015-12-03 10:52:10.000,2,Nordeste,CE,BOMPREÇO SUPERMERCADOS DO NORDESTE LTDA,HIPER BOMPREÇO,1,1.300451e+13,...,4711301.0,"COMÉRCIO VAREJISTA DE MERCADORIAS EM GERAL, CO...",N,102,Microcomputador / Produtos de Informática,105,Produto com vício,M,entre 41 a 50 anos,60843210.0
2234,2016,2016-09-15 14:25:44.000,2016-07-25 11:44:48.000,3,Sudeste,SP,ESSENCIAL COM ELETRÓNICOS MÓVEIS ELETRODOM,ESSENCIAL ELETRO / WWW.ESSENCIALELETRO.COM.BR,1,2.380889e+13,...,NaN,NaN,N,93,Fogão e Microondas,107,Não entrega/demora na entrega do produto,M,entre 51 a 60 anos,11089110.0

In [ ]:
frames = [df1, df2, df3, df4, df5] #Nome dos conjuntos de dados

In [ ]:
df_full = pd.concat(frames) #Concatena os datasets
df_full.shape

(13000, 23)

In [ ]:
df_full.sample(3) #Datasets concatenados

,AnoCalendario,DataArquivamento,DataAbertura,CodigoRegiao,Regiao,UF,strRazaoSocial,strNomeFantasia,Tipo,NumeroCNPJ,...,CNAEPrincipal,DescCNAEPrincipal,Atendida,CodigoAssunto,DescricaoAssunto,CodigoProblema,DescricaoProblema,SexoConsumidor,FaixaEtariaConsumidor,CEPConsumidor
910,2013,2013-08-01 16:46:57.000,2013-06-18 16:15:04.000,4,Sul,SC,VIDEOSERVICE ELETRONICA LTDA ME,VIDEO SERVICE ELETRONICA,1,2.163819e+12,...,9521500.0,REPARAÇÃO E MANUTENÇÃO DE EQUIPAMENTOS ELETROE...,N,96,Televisão / Vídeo Cassete / Filmadora / Video-...,106,Produto entregue diferente do pedido,F,entre 31 a 40 anos,88063300.0
308,2013,2013-07-23 09:31:07.000,2013-06-21 10:44:11.000,3,Sudeste,ES,LG ELECTRONICS DA AMAZÔNIA LTDA,LG ELECTRONICS,1,8.014500e+11,...,2640000.0,"FABRICAÇÃO DE APARELHOS DE RECEPÇÃO, REPRODUÇÃ...",S,101,"Telefone ( Convencional, Celular, Interfone, E...",105,Produto com vício,F,mais de 70 anos,29315002.0
2980,2014,2014-10-03 10:58:35.000,2014-02-06 14:44:58.000,2,Nordeste,BA,CLARO S.A.,CLARO,1,4.043254e+13,...,6120501.0,TELEFONIA MÓVEL CELULAR,N,186,Telefonia Fixa ( Plano de Expansão / Compra e ...,134,Cobrança indevida/abusiva,F,mais de 70 anos,41720100.0